name: Notify Discord about new/updated release

on:
  release:
    types: [published, edited]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Release Notification
        uses: SethCohen/github-releases-to-discord@v1
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          color: "5814783"
          username: "GitHub Releases"
          content: "||@everyone||"
          footer_title: "Released by ${{ github.actor }}"
          reduce_headings: true
